Theme: Update `CategoryContextBar ` with new loading UI.
WordPress/pattern-directory pull request #106
Opened 2021-05-12 02:08 UTC by StevenDufresne

This PR updates the loading state for the `CategoryContextBar` in reference to the new designs mentioned in #101.

These changes here are not enough to close the ticket; the pattern grid itself needs animation updates. This PR doesn't address those changes as the loading state for the pattern grid relies on yet to be made changes for #103.

**Notes**:
In some cases, there is some jank when the loader is animating out because it's also rendering the grid at the same time. It's most visible on quick internet connections. This should be a non-issue once the pattern grid loading is improved and rendering doesn't require such a significant layout recalculation.

See #101, #103

### Screenshots
![Screencast of animations](https://d.pr/i/j3mtmB.gif)

### How to test the changes in this Pull Request:

1. Create some block pattern categories
2. Create some patterns
3. Associate categories to patterns
4. Load `/`, click through categories
5. Expect to see UI matching designs.

2021-05-17 17:47 UTC, ryelle requested changes
The animation is working as designed 👍🏻 

It feels a little strange when clicking between categories, especially on a faster internet connection, since the start of text moves left & right with the spinner. That might be fine, since people _probably_ won't be doing this in real life, but I think we'll want to keep an eye on this once it's merged & the pattern grid loading is in place.

https://user-images.githubusercontent.com/541093/118532929-7fb9a080-b715-11eb-8e9c-e701c5939664.mov

Can you disable the animation when `prefers-reduced-motion: reduce` is set?

The class naming issue can be resolved in this PR, or we can have a followup issue to check all classnames for the naming conventions.

2021-05-17 17:47 UTC, ryelle commented on public_html/wp-content/themes/pattern-directory/css/components/_category-context-bar.scss
> +.category-context__bar__copy {
I missed this in a previous review, but class names should only have one `__` separating the root export (`category-context-bar` in CSS) & descriptor (`copy`). Any other separators should be hyphens `-`. So this should be `.category-context-bar__copy`. We're roughly following [the gutenberg standards](https://developer.wordpress.org/block-editor/contributors/code/coding-guidelines/).

2021-05-17 17:47 UTC, ryelle commented on public_html/wp-content/themes/pattern-directory/css/components/_category-context-bar.scss
> +.category-context__bar--is-hidden {
Where is this class used?

2021-05-18 01:18 UTC, StevenDufresne commented on public_html/wp-content/themes/pattern-directory/css/components/_category-context-bar.scss
> +.category-context__bar__copy {
Yep, makes sense. Thanks.

2021-05-18 01:23 UTC, StevenDufresne commented on public_html/wp-content/themes/pattern-directory/css/components/_category-context-bar.scss
> +.category-context__bar__copy {
There was originally a root component called `category-context` which I refactored out.

2021-05-18 02:26 UTC, StevenDufresne commented on public_html/wp-content/themes/pattern-directory/css/components/_category-context-bar.scss
> +.category-context__bar--is-hidden {
Removed.

2021-05-18 02:27 UTC, StevenDufresne commented
> It feels a little strange when clicking between categories, especially on a faster internet connection, since the start of text moves left & right with the spinner. That might be fine, since people _probably_ won't be doing this in real life, but I think we'll want to keep an eye on this once it's merged & the pattern grid loading is in place.

Agreed.

> Can you disable the animation when `prefers-reduced-motion: reduce` is set?

Yep, done in 55c9ec3.

2021-05-18 22:16 UTC, ryelle approved these changes
Thanks for updating the classnames. Motion is disabled when "reduced motion" is selected 👍🏻 

Good to merge!

2021-05-20 00:29 UTC, merged