Theme: Hook up pattern favorite functionality
WordPress/pattern-directory pull request #94
Opened 2021-05-05 22:14 UTC by ryelle

Fixes #52. This PR is based on #93, which sets up the API, and this PR sets up the data store and hooks up the actions to the `FavoriteButton`.

The `FavoriteButton` now has two props, `patternId` (required) and `showLabel` (defaults to true). This component handles fetching favorites, checking if this pattern (`patternId`) is favorited, and triggering the add/remove from favorite actions. `showLabel` is used to show/hide the "Add to favorites" text when we want to show a smaller button. The label is still available to screen reader users.

### Screenshots

<img width="330" alt="Screen Shot 2021-05-05 at 5 58 43 PM" src="https://user-images.githubusercontent.com/541093/117214999-98e45800-adcb-11eb-9e28-f32eb070326f.png">
<img width="644" alt="Screen Shot 2021-05-05 at 5 58 54 PM" src="https://user-images.githubusercontent.com/541093/117215000-98e45800-adcb-11eb-8699-06a9829aa6c6.png">
<img width="601" alt="Screen Shot 2021-05-05 at 5 59 01 PM" src="https://user-images.githubusercontent.com/541093/117215001-997cee80-adcb-11eb-82cb-2fab3016941c.png">

### How to test the changes in this Pull Request:

1. Visit the patterns list view, logged in
2. Try favoriting some patterns, they should turn red
3. Click into any favorited pattern, the button in the single pattern view should also be red
4. Unfavoriting patterns should also work, and persist around the site

If you're logged out, the buttons will still be there, but they're disabled (since favorites need a user). We can also just remove them or add a tooltip - wasn't sure which would be better.

2021-05-06 04:07 UTC, StevenDufresne commented
> If you're logged out, the buttons will still be there, but they're disabled (since favorites need a user). We can also just remove them or add a tooltip - wasn't sure which would be better.

Visually, it doesn't appear disabled so I think we **need** to do something before this merged. I'm fine if we just remove it for now since the list of favorites doesn't appear very discoverable yet -- at least in the current designs (Ie: How do I get there? ).
 Once it is surfaced better, we should probably push to log in users in most cases.

2021-05-10 20:51 UTC, ryelle commented
Updated to remove the ❤️ button until we know we have the ability to favorite patterns.

2021-05-11 00:13 UTC, StevenDufresne commented on public_html/wp-content/themes/pattern-directory/src/store/test/resolvers.js
> +	it( 'yields with the requested categories', async () => {
Thanks for catching this.

2021-05-11 00:37 UTC, StevenDufresne requested changes
This is looking good. 

Can we left-align the button on mobile?

![](https://d.pr/i/NP9row.png)

2021-05-11 00:39 UTC, StevenDufresne commented
Also, we still have a favorite button in the PHP template and you can see the flash when you throttle your connection. We should probably open up a ticket to deal with the out-of-sync content-grid template because the problem exists for all the buttons on the page. It's most obvious for the favorite button because it is absent by default.

https://github.com/WordPress/pattern-directory/blob/efb41c76f60329897303ee69d6105068e8b02a13/public_html/wp-content/themes/pattern-directory/template-parts/content-grid.php#L22

[Here is a screencast](https://d.pr/i/WQTPQB) of the flash.

2021-05-11 17:33 UTC, ryelle commented
I've switched this to center the buttons at the mobile breakpoint (480px)
<img width="518" alt="Screen Shot 2021-05-11 at 1 25 52 PM" src="https://user-images.githubusercontent.com/541093/117859226-b9ddfa80-b25c-11eb-923f-41bf3447dc63.png">

Then when the buttons wrap, they stay centered:
<img width="406" alt="Screen Shot 2021-05-11 at 1 26 06 PM" src="https://user-images.githubusercontent.com/541093/117859227-ba769100-b25c-11eb-8d9f-eebcc80a8224.png">

No change on larger screens:
<img width="1264" alt="Screen Shot 2021-05-11 at 1 26 23 PM" src="https://user-images.githubusercontent.com/541093/117859229-ba769100-b25c-11eb-9bd2-1f8aab2df0eb.png">

2021-05-11 17:48 UTC, ryelle commented
> Also, we still have a favorite button in the PHP template and you can see the flash when you throttle your connection.

👍🏻  opened #104, but I think it's worth waiting on implementing anything until the dust settles a bit. I dropped two possible approaches in a comment.

2021-05-12 00:11 UTC, StevenDufresne approved these changes
Good to go! 🥳

2021-05-17 18:28 UTC, merged